const ListProduct = [
    {
        id : 1,
        name : "Juicy Grapes",
        oldprice : 92,
        price : 86,
        quality: 200,
        rating : 4,
        category : "fruits",
        season: "Spring",
        nameCompany: "Fruit Company",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/1.jpg"
    },
    {
        id : 2,
        name : "Fresh Banana",
        oldprice : 43,
        price : 40,
        quality: 200,
        rating : 4,
        category : "fruits",
        season: "Summer",
        nameCompany: "Fruit Company 2",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/2.jpg"
    },
    {
        id : 3,
        name : "Red Capsicum",
        oldprice : 37,
        price : 34,
        quality: 200,
        rating : 4,
        category : "fruits",
        season: "Autumn",
        nameCompany: "Fruit Company 3",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/3.jpg"
    },
    {
        id : 4,
        name : "Rippen Mango",
        oldprice : 28,
        price : 20,
        quality: 200,
        rating : 3,
        category : "fruits",
        season: "Spring",
        nameCompany: "Fruit Company 4",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/4.jpg"
    },
    {
        id : 5,
        name : "Farm's Onion",
        oldprice : 50,
        price : 40,
        quality: 200,
        rating : 4,
        category : "fruits",
        season: "Spring",
        nameCompany: "Fruit Company 1",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/5.jpg"
    },
    {
        id : 6,
        name : "Fresh Coconut",
        oldprice : 80,
        price : 50,
        quality: 200,
        rating : 4,
        category : "vegetables",
        season: "Spring",
        nameCompany: "Fruit Company 2",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/6.jpg"
    },
    {
        id : 7,
        name : "Tangerin Juice",
        oldprice : 47,
        price : 44,
        quality: 200,
        rating : 4,
        category : "vegetables",
        season: "Spring",
        nameCompany: "Fruit Company 4",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/7.jpg"
    },
    {
        id : 8,
        name : "Pine Apple",
        oldprice : 37,
        price : 33,
        quality: 200,
        rating : 4,
        category : "fruits",
        season: "Spring",
        nameCompany: "Fruit Company 4",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/8.jpg"
    },
    {
        id : 9,
        name : "Fresh Cucumber",
        oldprice : 92,
        price : 86,
        quality: 200,
        rating : 4,
        category : "vegetables",
        season: "Spring",
        nameCompany: "Fruit Company 3",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/9.jpg"
    },
    {
        id : 10,
        name : "Juicy Grapes Asia",
        oldprice : 52,
        price : 41,
        quality: 200,
        rating : 4,
        category : "fruits",
        season: "Spring",
        nameCompany: "Fruit Company",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/10.jpg"
    },
    {
        id : 11,
        name : "Fresh Cucumber Asia",
        oldprice : 92,
        price : 86,
        quality: 200,
        rating : 4,
        category : "vegetables",
        season: "Spring",
        nameCompany: "Fruit Company",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/11.jpg"
    },
    {
        id : 12,
        name : "Fresh Grape",
        oldprice : 92,
        price : 86,
        quality: 200,
        rating : 4,
        category : "juices",
        season: "Spring",
        nameCompany: "Fruit Company",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/12.jpg"
    },
    {
        id : 13,
        name : "Beans",
        oldprice : 92,
        price : 86,
        quality: 200,
        rating : 4,
        category : "fruits",
        season: "Spring",
        nameCompany: "Fruit Company",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/13.jpg"
    },
    {
        id : 14,
        name : "Onion Asia",
        oldprice : 22,
        price : 16,
        quality: 200,
        rating : 4,
        category : "juices",
        season: "Spring",
        nameCompany: "Fruit Company",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/14.jpg"
    },
    {
        id : 15,
        name : "Orange Asia",
        oldprice : 27,
        price : 23,
        quality: 200,
        rating : 4,
        category : "fruits",
        season: "Spring",
        nameCompany: "Fruit Company",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/15.jpg"
    },
    {
        id : 16,
        name : "Fresh Grape Kiwi",
        oldprice : 31,
        price : 25,
        quality: 200,
        rating : 4,
        category : "juices",
        season: "Spring",
        nameCompany: "Fruit Company",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/16.jpg"
    },
    {
        id : 17,
        name : "Purple Cabbage America",
        oldprice : 92,
        price : 86,
        quality: 200,
        rating : 4,
        category : "juices",
        season: "Spring",
        nameCompany: "Fruit Company",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/17.jpg"
    },
    {
        id : 18,
        name : "Onion Green",
        oldprice : 44,
        price : 39,
        quality: 200,
        rating : 4,
        category : "juices",
        season: "Spring",
        nameCompany: "Fruit Company",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/18.jpg"
    },
    {
        id : 19,
        name : "Tomato Asia",
        oldprice : 27,
        price : 21,
        quality: 200,
        rating : 4,
        category : "bread",
        season: "Spring",
        nameCompany: "Fruit Company",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/19.jpg"
    },
    {
        id : 20,
        name : "Watermelon",
        oldprice : 24,
        price : 20,
        quality: 200,
        rating : 4,
        category : "bread",
        season: "Spring",
        nameCompany: "Fruit Company",
        desc : "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        img : "https://template.hasthemes.com/naturecircle/naturecircle/assets/img/product/20.jpg"
    },
]

export default ListProduct;